name: mu
version: 0.1.0.0
github: Futarimiti/mu
license: MIT
author: Carman Fu
license-file: LICENSE
maintainer: futarimiti@163.com
copyright: Carman Fu 2024
extra-source-files:
  - README.md
synopsis: Personal music downloader & player
category: Sound
description: Please see the README on GitHub at <https://github.com/Futarimiti/mu#readme>
data-dir: resources
data-files:
  - messages.dhall
  - fileinfo.dhall
default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - FlexibleContexts
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - OverloadedRecordDot
  - QuasiQuotes
  - StrictData
  - TemplateHaskell
dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - dhall
  - directory
  - exceptions
  - filepath
  - monad-logger
  - mtl
  - optparse-applicative
  - process
  - random-shuffle
  - serialise
  - string-interpolate
  - temporary
  - text
  - transformers          ^>=0.6.0.0
  - yaml
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmonomorphism-restriction
  - -Wno-name-shadowing
  - -Wpartial-fields
  - -Wredundant-constraints
  - -O2
executables:
  mu:
    main: Main.hs
    source-dirs:
      - app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
