name: mu
data-dir: resources
data-files: []
dependencies:
  - aeson
  - barbies
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - data-default
  - dhall
  - directory
  - exceptions
  - filepath
  - generic-lens
  - lens
  - monad-logger
  - mtl
  - optparse-applicative
  - process
  - random-shuffle
  - safe-exceptions
  - serialise
  - string-interpolate
  - temporary
  - text
  - transformers          ^>=0.6.0.0
  - yaml
default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralisedNewtypeDeriving
  - ImportQualifiedPost
  - ImpredicativeTypes
  - InstanceSigs
  - LambdaCase
  - MultiWayIf
  - OverloadedLabels
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilyDependencies
  - TypeOperators
  - UndecidableInstances
  - UnicodeSyntax
  - ViewPatterns
ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wmonomorphism-restriction
  - -Wno-missing-export-lists
  - -Wno-name-shadowing
  - -Wpartial-fields
  - -Wredundant-constraints
executables:
  mu:
    main: Main.hs
    source-dirs:
      - app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
library:
  source-dirs: src
